import Navbar from './components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Opentable',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className='bg-gray-100 min-h-screen w-screen'>
      <main className='max-w-screen-2xl m-auto bg-white'>
        <Navbar />
        {children}
      </main>
    </main>
  )
}
